### ISSUE TITLE
Project clarifications

### ISSUE THREAD

**Issue by phillycc** [IZEA/interview#5]
@fusion2004 Intended interview workflow? Fork this repo, create separate project folder, and submit PR when done building out mockup? 
Also, do the instructions forbid use of html5 boilerplate/build automation tools, such as those in Yeoman or [Todd Motto's FireShell](http://getfireshell.com/)?

**Comment by benhanzl** [comment]
@phillycc There isn't much to gain from forking it, since we don't provide a starting point for you. I would suggest creating your own repo and emailing us the link when you are done.

You are good to use HTML5 boilerplate and whatever build tools you want, just not a CSS framework (such as Bootstrap).

**Comment by phillycc** [comment]
@benhanzl Very cool, Ben. Thanks!

**Comment by benhanzl** [comment]
@phillycc Good luck!

**Comment by phillycc** [comment]
:thumbsup:
